### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by wbrickner** [DankDumpster/mouse-rs#13]
Hi!
Would you be willing to relicense under MIT?

I ask because:

- Most of the rust ecosystem uses an MIT license.
- MIT provides a few additional freedoms to the end user that GPL does not (source publishing, etc)
- I'd like to use `mouse-rs` in a public library of my own, and I'd like to release it under an MIT license,
but would not be able to as `mouse-rs` is GPL.

If not, that's fine, I thought I would ask.

Thank you!

**Comment by AltF02** [comment]
Hi, when I created this project I just slapped on gpl and didn't think of the implications that it brings by being a library. I'm open to switching to MIT, but I will need permission from every contributor.

@s1gtrap @mxve @billyb2 @DTibbs

**Comment by wbrickner** [comment]
I've seen it done once before like:

>To agree to relicensing, comment with:
>
> ```
> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
> ```

Although that is "dual MIT/Apache-2.0", which is not the same as MIT, and the exact relicensing choice is not mine to make.

**Comment by AltF02** [comment]
I'd like to avoid dual licensing, especially for such a small  project. I hope you understand :)

**Comment by billyb2** [comment]
I totally understand and give my full permission

**Comment by mxve** [comment]
You have my permission to change the license to MIT

**Comment by s1gtrap** [comment]
I'm good with whatever, but why not dual @AltF02? I always go Apache+MIT regardless of size

**Comment by AltF02** [comment]
Mainly because it would require GPL+MIT? Which afaik defeats the purpose of switching to MIT? I'm not too familiar with licenses honestly, I'm not a lawyer

**Comment by wbrickner** [comment]
Yes, not in favor of `GPL + MIT`. 

I think the options being referenced are `MIT` or `MIT + Apache 2.0`, the latter dual license scheme being most popular in the rust ecosystem as far as I'm aware.

---

I do not know what _specific_ advantages come from dual licensing under `MIT + Apache 2.0`, but my understanding is that it provides flexibility as end users (and transitive end users, etc) can choose between the two as they like.

I believe the process is identically simple: collect written consent from contributors, and set `license = "MIT OR Apache-2.0"` in `Cargo.toml`

**Comment by s1gtrap** [comment]
Oh no for sure, I was definitely also thinking `"MIT OR Apache-2.0"` as @wbrickner had suggested.

It's my understanding that Apache 2 is a precaution to avoid patent suits stemming from bad faith contributions, but INAL either so I'd take that with a _ton_ of salt 😂

**Comment by AltF02** [comment]
Yeah, I'm open to doing that, sorry I thought you meant dual licensing to the current GPL+MIT in the case not everyone responds

**Comment by DTibbs** [comment]
You have my permission to change the license.

**Comment by AltF02** [comment]
Thank you! Seems like we've got everyone now, I will make a PR soon

**Comment by AltF02** [comment]
I created a pr with a dual license, I'm assuming everyone is okay with that?
