### ISSUE TITLE
How can I get current location of cursor?

### ISSUE THREAD

**Issue by alloc33** [DankDumpster/mouse-rs#17]
How can I get current location of cursor?

**Comment by alloc33** [comment]
Figured out by digging into lib. I suggest to add more info to readme :)

**Comment by dylhack** [comment]
The docs are generated there's a badge that links to the stable version. I believe you're looking for [get_position](https://docs.rs/mouse-rs/latest/mouse_rs/struct.Mouse.html#method.get_position)
