### ISSUE TITLE
Mouse move does not generate events on macOS

### ISSUE THREAD

**Issue by bwpge** [DankDumpster/mouse-rs#19]
Really appreciate the work done on this library, thank you :)

**Issue**

The [`Mouse::move_to`](https://github.com/AltF02/mouse-rs/blob/7d2ca5d09ab33b12d7fcc437d96a49416bc359b5/src/sys/macos.rs#L66-L73) method under `sys::macos` does not fire an event when the mouse is moved. From Apple docs, [`CGDisplayMoveCursorToPoint`](https://developer.apple.com/documentation/coregraphics/1455258-cgdisplaymovecursortopoint) does not generate events. The result is that on macOS, the cursor is moved but nothing in the UI reacts to those movements (unlike Windows, where `SetCursorPos` generates mouse moved messages in the Win32 message loop).

**Potential Solution**

Use [`core_graphics::event::CGEvent::new_mouse_event`](https://docs.rs/core-graphics/latest/core_graphics/event/struct.CGEvent.html#method.new_mouse_event) with the `CGEventType` variant [`MouseMoved`](https://docs.rs/core-graphics/latest/core_graphics/event/enum.CGEventType.html#variant.MouseMoved).

**Commentary**

I'm not sure if this intentional or not, but it is divergent from the Windows behavior. [`SetCursorPos`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcursorpos) does fire events (or messages) as a part of its implementation in the Win32 API.

Additional consideration is that generating mouse moved events on macOS may prompt the user to enable the application to take control through accessibility features, which may not be clear to the library consumer or the user of the resulting application.

Edit: fixed typo

**Comment by AltF02** [comment]
Hi, I unfortunately don't have access to a macos machine. So I'm unable to check, would it be possible for you to create a pr that changes this behavior? As this is not intended

**Comment by bwpge** [comment]
Sure thing, will do

**Comment by bwpge** [comment]
This issue is closed by #21
